server:
  port: 8708

spring:
  application:
    name: service-data #服务之间的调用就是通过这个名字
  zipkin:
    base-url: http://localhost/9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379   # Redis服务器连接端口
    password:           # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    timeout: 300  # 连接超时时间（毫秒）
  cache:
    redis:
       timeToLive: 1000000 #毫秒

eureka:
  client:
    service-url:
      default-Zone: http://peer1:8761/euraka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


