server:
  port: 8769

spring:
  profiles:
    include: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/  #如果这个8769注册中心宕机了,就依靠8761这个注册服务中心来支撑
    registerWithEureka: false #避免server当作客户端注册到自身
    fetchRegistry: false #避免server当作客户端注册到自身