server:
  port: 8989

spring:
  application:
    name: service-hi #服务之间的调用就是通过这个名字
  zipkin:
    base-url: http://localhost/9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/euraka/
